EcommerceInLocal/Ecommerce.Web/Controllers/CartController.cs
using Autofac;
using Ecommerce.Web.Models;
using Framework.Entity;
using Framework.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace Ecommerce.Web.Controllers
{
    public class CartController : AreaBaseController<CartController>
    {
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }       
        protected IShoppingCartServices _cartServices;
        public CartController(ILifetimeScope scope,IUserAccessor userAccessor,
            IShoppingCartServices cartServices) :base(scope,userAccessor) 
        {
                _cartServices= cartServices;    
        }
        [Authorize]
        public IActionResult IndexCart()
        {
            Guid UserId = CurrentUser != null ? CurrentUser.Id : Guid.Empty;
            var model = new ShoppingCartVM();
            model.OrderHeader = new OrderHeader();
           
            model.ListCart= _cartServices.GetShoppingCart(UserId);
            model.OrderHeader.OrderTotal = 0;
            foreach (var item in model.ListCart)
            {
                model.OrderHeader.OrderTotal += Result(item.Product.Price, item.Count);
            }
            return View(model);
        }
        private double Result(double price,int count)
        {
            return price * count;   
        }
        public IActionResult Plus(int cartId)
        {
            _cartServices.UpdateCart(cartId);
            return RedirectToAction(nameof(IndexCart));
        }
        public IActionResult Minus(int cartId)
        {
            _cartServices.MinusCart(cartId);
            return RedirectToAction(nameof(IndexCart));
        }
        public IActionResult Remove(int cartId) 
        {
            _cartServices.RemoveCart(cartId);
            return RedirectToAction(nameof(IndexCart));
        }

        public IActionResult Summary()
        {
            Guid UserId = CurrentUser != null ? CurrentUser.Id : Guid.Empty;

            return View();
        }
    }
}

EcommerceInLocal/Ecommerce.Web/Controllers/CoverController.cs
using Ecommerce.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Autofac;
using Ecommerce.Web.Models.CoverModelFolder;
using Framework.Exceptions;
using Ecommerce.Web.Models.SellerModel;

namespace Ecommerce.Web.Controllers
{
    public class CoverController : AreaBaseController<CoverController>
    {
        public CoverController(ILifetimeScope scope,IUserAccessor userAccessor):base(scope, userAccessor)
        {
        }
        public IActionResult IndexCO()
        {
            var model = _scope.Resolve<CoverVM>();
            return View(model);
        }

        public IActionResult AddSeller()
        {
            var model = _scope.Resolve<CreateSellerModel>();
            return View(model);
        }
        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult AddSeller(CreateSellerModel model)
        {
            model.ResolveDependency(_scope);

            if (ModelState.IsValid)
            {
                try
                {
                    model.AddSeller();
                    model.Response = new ResponesModelTwo("created successfully", ResponseType.Success);
                    return View(model);
                }
                catch (DuplicationException2 ex)
                {
                    model.Response = new ResponesModelTwo(ex.Message, ResponseType.Failure);
                }
                catch (Exception ex)
                {
                    model.Response = new ResponesModelTwo("failed! ", ResponseType.Failure);
                }
            }
            return View(model);
        }


        public IActionResult Add()
        {
            var model = _scope.Resolve<CreateCover>();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Add(CreateCover model)
        {
            model.ResolveDependency(_scope);
            if (ModelState.IsValid)
            {
                try
                {
                    model.Add();
                    ViewResponse("Success", ResponseType.Success);
                    return RedirectToAction(nameof(Index));
                }
                catch (DuplicationException ex)
                {
                    ViewResponse("Duplicate", ResponseType.Duplicate);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ViewResponse("Failure", ResponseType.Failure);

                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model=_scope.Resolve<EditCover>();
            //var model = new EditCover();
            model.Load(id);
            return View(model); 
        }
        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Edit(EditCover editCover)
        {
            editCover.ResolveDependency(_scope);
            if(ModelState.IsValid)
            {
                try
                {
                    editCover.EditModel();
                    ViewResponse("Success", ResponseType.Success);
                    return RedirectToAction(nameof(Index));
                } 
                catch(DuplicationException ex)
                { 
                    ViewResponse("Duplicate",ResponseType.Duplicate);   
                    return RedirectToAction(nameof(Index)); 
                }
                catch(Exception ex)
                {
                    ViewResponse("Failure", ResponseType.Failure);
                }
            }
            return View(editCover);
        }
        public IActionResult GetCover()
        {
            var tableModel = new DataTablesAjaxRequestModel(Request);
            var model = _scope.Resolve<CoverVM>();
            var data = model.GetCover(tableModel);
            return Json(data);
        }

    }
}

EcommerceInLocal/Ecommerce.Web/Views/Shared/_ActionMessage.cshtml
@* @model ResponesModelTwo

@if(Model != null)
{
<div class="alert alert-dismissible @Model.StyleCssClass" id="response-alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h5><i class="icon fas @Model.IconCssClass"></i> @Model.Title</h5>
    @Model.Message
</div>

} *@

EcommerceInLocal/Ecommerce.Web/Views/Shared/_Layout.cshtml
@model BaseModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommerce.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" /> 
    @RenderSection("PageStyle", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand"  asp-controller="Home" asp-action="IndexH">Ecommerce.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="IndexC">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cover" asp-action="IndexCO">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="IndexP">Product</a>
                        </li>
                        <li style="color:darkseagreen;">
                            <a  asp-controller="Cart" asp-action="IndexCart" class="nav-link">
                               @*  @{
                                    var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart);
                                } *@
                                <i class="fas fa-shopping-cart"></i> &nbsp; @* (@count) *@
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>


                     <partial name="_LoginPartial" /> 
                     

                 </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <partial name="_ResponsePartial" />
 
@*             <partial name="_ActionMessage" model="@Model.Response2" />
 *@  
              @RenderBody()
            

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ecommerce.Web - <a  asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>

    @RenderSection("PageScript", false)

    <script src="~/js/site.js" asp-append-version="true"></script>

    <partial name="_ToasterMessage" model="@Model.Response" />
    
   <script>
        $(function () {

            $("#response-alert").fadeTo(5000, 500).slideUp(500, function () {
                $("#response-alert").slideUp(500);
            });

        });
    </script>
</body>
</html>

EcommerceInLocal/Ecommerce.Web/Views/Shared/_ResponsePartial.cshtml
@using Ecommerce.Web.Models

@if(TempData.Peek<ResponseModel>("ResponseMessage") != null)
{
    var response = TempData.Get<ResponseModel>("ResponseMessage");
    <div class="alert alert-@(response.Type.ToString().ToLower())" role="alert">
        @response.Message
    </div>
} 
@* else
{
    var response3 = TempData.Get<ResponseModel>("ResponseMessage");
    <div class="alert alert-@(response3.Type.ToString().ToLower())" role="alert">
        @response3.Message
    </div>
} *@

EcommerceInLocal/Ecommerce.Web/Views/Shared/_ToasterMessage.cshtml
@model ResponesModelTwo

@if (Model != null)
{
    if (Model.ToasterClass == "success")
    {
        <script>
            $(function () {
                toastr.success('@Model.Message')
            });
        </script>
    }
    else
    {
        <script>
            $(function () {
                toastr.error('@Model.Message')
            });
        </script>
    }

}